---
title: "dealing with missing data"
output: html_notebook
---

```{r}
library(RepDataPeerAssessment1)

data("activity")
head(activity)
```

```{r}

```

```{r}
activity
```



```{r}
x0 <- activity$steps
summary(x0)
```

We have 2304 NA's.

How important is it?
```{r}
mean(is.na(x0))
```

We have 13% of missing values.

```{r}
missing.days <- 
```


## Using `dplyr`

How many values are zeros?
```{r message=FALSE}
library(dplyr)

filter(activity) %>%
  summarize(zeros = mean(steps != 0, na.rm = TRUE))
```

```{r}

```





## Using the mean to replace NA values
Source: https://www.r-bloggers.com/example-2014-5-simple-mean-imputation/

```{r}
df = data.frame(x = 1:20, y = c(1:10,rep(NA,10)))
head(df)
tail(df)
```

```{r}
df$y[is.na(df$y)] = mean(df$y, na.rm = TRUE)
```

```{r}
tail(df)
```

### Alternative
```{r}
# alternative
df = data.frame(x = 1:20, y = c(1:10,rep(NA,10)))
head(df)
tail(df)

df = transform(df, y = ifelse(is.na(y), mean(y, na.rm=TRUE), y))
tail(df)
```

In the first example, we identify elements of y that are NA, and replace them with the mean, if so. In the second, we test each element of y; if it is NA, we replace with the mean, otherwise we replace with the original value. 

